open = """
1. "I know your inbox is likely overflowing, so I'll get straight to the point without taking up too much of your time."
2. "I promise this isn’t another run-of-the-mill email – I’ve done my homework on [Company Name] and am eager to explain why we could be a great match."
3. "[Recruiter's Name], I hope this message finds you well. I'll keep this brief, but I believe it’s worth your attention."
4. "In the time it takes to grab your morning coffee, let me introduce myself and share how I might solve a problem for [Company Name]."
5. "I know you’re juggling multiple tasks, so I’ll be quick and to the point—here’s how I can help [Company Name] achieve its goals."
6. "What if I told you I could help [Company Name] [achieve specific goal]? Intrigued? Let me explain."
7. "Your recent article on [Company Blog/LinkedIn] about [topic] caught my eye. Here’s why I think I could help bring those ideas to life at [Company Name]."
8. "I’ve been keeping an eye on [Company Name] and am impressed by your work. I believe my skills could be a valuable addition to your team."
9. "Imagine having a [Your Job Title] who could [solve specific problems/achieve specific goals]. That’s exactly what I’m offering [Company Name] today."
10. "I know cold emails can be hit or miss, but I’m hoping this one stands out as exactly what [Company Name] needs in a [Your Job Title]."
11. "In a sea of generic applications, I’m here to offer [Company Name] something refreshingly specific: my unique blend of skills in [Your Key Skill Area]."
12. "I assure you I’m not a spam bot, just a passionate [Your Job Title] who’s been following [Company Name] and is excited about the chance to contribute."
"""